### PR TITLE
#287: Fix for NPE that is throw when trying to link internally to pro…

### PR DESCRIPTION
**Pull request by williamschey**
Hi @bsorrentino, thanks for the plugin. Works great!. I am getting the same issue as @FromirDread. I was able to fix it by dealing with the Nulls.

### CODE REVIEW

**Comment by bsorrentino** [comment]
Thanks @williamschey for PR

I've used Optional for deal with such problems, I'll review the Optional usage and merge your PR soon

**Comment by williamschey** [comment]
Hey @bsorrentino, thanks for the crazy quick response. You are right, Optional can definitely deal with it but I think it needed the ofNullable rather than the of. Updated the PR to reflect it. Hope it helps. Thanks again.

**Comment by bsorrentino** [comment]
Hi @williamschey  I've deployed the release `7.12-SNAPSHOT` with your fix

I'll release official version soon

**Comment by williamschey** [comment]
Thanks @bsorrentino, tried it out this morning and works a treat! Thanks again.

**Pull request merged**
