### PR TITLE
Allow for attachments to include all files in a directory

### PR DESCRIPTION
**Pull request by jprafael**

### CODE REVIEW

**Comment by bsorrentino** [comment]
Hi thanks for PR it is very useful 

I've merged it on branch [feature/pull#137](https://github.com/bsorrentino/maven-confluence-plugin/tree/feature/pull%23137)

I've bit updated your code preferring use `listFiles( FileFilter )`

```java
                attachmentFile.listFiles( new FileFilter() {
                    @Override
                    public boolean accept(File file) {
                        
                        final Site.Attachment fileAttachment = new Site.Attachment();
                        fileAttachment.setName(file.getName());
                        fileAttachment.setUri(file.toURI());
                        fileAttachment.setComment(attachment.getComment());
                        fileAttachment.setVersion(attachment.getVersion());
                        generateAttachment(confluence, confluencePage, fileAttachment);
                        return false;
                    }
                });

```

**Comment by jprafael** [comment]
Hey! I'm not 100% sure on that change since the `FileFilter` is meant to be used as a predicate for the list of files that is returned from `listFiles` and not as a side-effect-full function. Nonetheless, i'm OK if you prefer it this way.

Since you merged it to the feature/pull#137 branch what should I do with this MR? want me to close it?

**Comment by bsorrentino** [comment]
I'll close it after tests pass

**Comment by bsorrentino** [comment]
I've used  [Files.newDirectoryStream](https://docs.oracle.com/javase/7/docs/api/java/nio/file/Files.html#newDirectoryStream(java.nio.file.Path,%20java.lang.String)) to achieve also the [glob pattern](https://docs.oracle.com/javase/7/docs/api/java/nio/file/FileSystem.html#getPathMatcher(java.lang.String))

**example**
```xml 
<!-- include all png files from myfolder -->
<attachment
  name="*.png"
  uri="myfolder"
  comment="file from myfolder"
  contentType="image/png"
  version="1"/>

<!-- include all files from myfolder -->
<attachment  
  uri="myfolder"
  comment="file from myfolder"  
  version="1"/>
```

**Comment by jprafael** [comment]
Thats even better. Thanks!

**Pull request merged**
